# Configuración para publicar en Netlify
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Las llamadas a PDFMonkey pasan por su función (para que no haya error de CORS)
[[redirects]]
  from = "/api/pdfmonkey/*"
  to = "/.netlify/functions/pdfmonkey/:splat"
  status = 200

# Las llamadas al correo pasan por su función
[[redirects]]
  from = "/api/correo"
  to = "/.netlify/functions/correo"
  status = 200

# Como es una sola aplicación, cualquier otra ruta lleva al index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
